#!/bin/sh

case "$1" in
  start)
    echo "Iniciando BusyBox HTTPD"
    httpd -p 80 -h /www
    ;;
  stop)
    echo "Parando BusyBox HTTPD"
    killall httpd
    ;;
  restart)
    killall httpd
    httpd -p 80 -h /www
    ;;
  *)
    echo "Uso: $0 {start|stop|restart}"
    exit 1
esac

exit 0
